version: '3'

networks:
  yii_network:
    driver: bridge

services:
  db:
    image: mariadb:10.5
    networks:
      - yii_network
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yii_db
      MYSQL_USER: yii_user
      MYSQL_PASSWORD: yii_password

  yii_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/app
    ports:
      - 8080:80
      - 8081:8081
    networks:
      - yii_network
    depends_on:
      - db
    links:
      - db

volumes:
  db_data: {}
